### PR TITLE
change display and fixes to contains.

### PR DESCRIPTION
**Pull request by karlnicholas**
change display and fixes to contains.

### CODE REVIEW

**Comment by alternatebow** [comment]
Oh yeah... My bad. I completely forgot about it.

**Comment by karlnicholas** [comment]
Actually I think it still needs to be changed. An int-index isn't of any use in other methods.

**Comment by alternatebow** [comment]
So is our definition of the method incorrect?

**Comment by karlnicholas** [comment]
**Returns first instance of element if it exists.**
I think this is what needs to be implemented and it makes sense, so the method signature should be

    public T contains(T anEntry);

**Comment by alternatebow** [comment]
Hmm... alright then. We'll change it.

**Comment by karlnicholas** [comment]
Sounds good. I'll update it.

**Pull request merged**
